// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7EmrE5KB_9qgdadYi6E4HwPqfrsNJ1Cw',
    appId: '1:17592326757:web:3c5d64d1843bd1a1ee848c',
    messagingSenderId: '17592326757',
    projectId: 'crud-task-2d044',
    authDomain: 'crud-task-2d044.firebaseapp.com',
    storageBucket: 'crud-task-2d044.firebasestorage.app',
    measurementId: 'G-YBCKJC290N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByDN7w6veCeJcqaMKkSwBzzs55PqqjIx8',
    appId: '1:17592326757:android:ff832108d2bf75c2ee848c',
    messagingSenderId: '17592326757',
    projectId: 'crud-task-2d044',
    storageBucket: 'crud-task-2d044.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaIc8YJoTUdWcejxj-kMbebkw7h1Dn1ww',
    appId: '1:17592326757:ios:aa845b583817eb25ee848c',
    messagingSenderId: '17592326757',
    projectId: 'crud-task-2d044',
    storageBucket: 'crud-task-2d044.firebasestorage.app',
    iosBundleId: 'com.example.crudTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaIc8YJoTUdWcejxj-kMbebkw7h1Dn1ww',
    appId: '1:17592326757:ios:aa845b583817eb25ee848c',
    messagingSenderId: '17592326757',
    projectId: 'crud-task-2d044',
    storageBucket: 'crud-task-2d044.firebasestorage.app',
    iosBundleId: 'com.example.crudTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7EmrE5KB_9qgdadYi6E4HwPqfrsNJ1Cw',
    appId: '1:17592326757:web:8c5e483238b0cf28ee848c',
    messagingSenderId: '17592326757',
    projectId: 'crud-task-2d044',
    authDomain: 'crud-task-2d044.firebaseapp.com',
    storageBucket: 'crud-task-2d044.firebasestorage.app',
    measurementId: 'G-BT9TKN1BFH',
  );
}
